apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "helm.fullname" . }}
  labels:
    {{- include "helm.labels" . | nindent 4 }}
spec:
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      {{- include "helm.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "helm.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "helm.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /liveness
              port: http
          readinessProbe:
            httpGet:
              path: /readiness
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: GITTER_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ include "helm.fullname" . }}-gitter
                  key: token
            - name: SLACK_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ include "helm.fullname" . }}-slack
                  key: token
            - name: SLACK_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: {{ include "helm.fullname" . }}-slack
                  key: clientId
            - name: SLACK_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "helm.fullname" . }}-slack
                  key: clientSecret
            - name: SLACK_VERIFICATION_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ include "helm.fullname" . }}-slack
                  key: verificationToken
            - name: POSTGRES_USER
              value: {{ .Values.global.db.user | quote }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.global.db.password | quote }}
            - name: POSTGRES_HOST
              value: {{ include "helm.fullname" . }}-postgresql
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_DATABASE
              value: {{ .Values.global.db.database | quote }}
            - name: APP_PORT
              value: {{ .Values.service.port | quote }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}