apiVersion: v1
kind: Secret
metadata:
  name: {{ include "helm.fullname" . }}-gitter
type: Opaque
data:
  token: {{ .Values.secrets.gitter.token | b64enc }} 
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "helm.fullname" . }}-slack
type: Opaque
data:
  {{- with .Values.secrets.slack }}
  token: {{ .token | b64enc }}
  clientId: {{ .clientId | b64enc }}
  clientSecret: {{ .clientSecret | b64enc }}
  verificationToken: {{ .verificationToken | b64enc }}
  {{- end }}